import { View, Text, TouchableOpacity, StyleSheet} from "react-native";
import { useAuth } from "../../context/AuthContext";
import React, { useState} from "react";
import { logConsent } from "../../services/consentServices";
import { useNavigation } from "@react-navigation/native";



const ConsentForm = () => {

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(false);
  const { user } = useAuth();
  const navigation = useNavigation();


  const handleSubmit = async () => {
    if (!user) return;
    try {
      setLoading(true);
      setError(null);
      setSuccess(false);
      const idToken = await user.getIdToken(true);
      console.log("idToken THIS IS THE INVALID", idToken);
      const consentData = {
        signed: true,
        signed_date: new Date().toISOString()
      }
      await logConsent(consentData, idToken);
      setSuccess(true);
      navigation.navigate('DashboardTabs', { screen: 'Today' }); 
    } catch(error) {
      console.error("Failed to update the Consent Form", error);
      setError("Failed to update Consent Form");
    } finally {
      setLoading(false);
    }
  }

  if (loading) return <Text>Loading...</Text>
  if (error) return <Text>{error}</Text>
  if (success) return <Text>Thank you for your consent!</Text>
  return (
    <View style={styles.container}>
      <Text style={styles.heading}>Consent to Participate</Text>
      <Text style={styles.commonText}>Welcome to the AsthmaTracker App!</Text>
      <Text style={styles.commonText}>Before using the app, please review the following:</Text>
      <View style={styles.bulletedListContainer}>
        <Text style={styles.bulletedList}>.</Text>
        <Text style={styles.bulletedListText}>
          I understand the app collects personal asthma health information.
        </Text>
      </View>
      <View style={styles.bulletedListContainer}>
        <Text style={styles.bulletedList}>.</Text>
        <Text style={styles.bulletedListText}>
          I consent to the collection, storage, and use of my data to support my asthma management.
        </Text>
      </View>
      <View style={styles.bulletedListContainer}>
        <Text style={styles.bulletedList}>.</Text>
        <Text style={styles.bulletedListText}>
          I know I can withdraw consent at any time by contacting support.
        </Text>
      </View>
      <View style={styles.bulletedListContainer}>
        <Text style={styles.bulletedList}>.</Text>
        <Text style={styles.bulletedListText}>
          I acknowledge that the app does not replace medical advice from a healthcare provider.
        </Text>
      </View>
      <View style={styles.bulletedListContainer}>
        <Text style={styles.bulletedList}>.</Text>
        <Text style={styles.bulletedListText}>
          I understand that the app uses artificial intelligence (AI) to analyze my logged data and 
          provide informational insights and educational content.
        </Text>
      </View>
      <View style={styles.bulletedListContainer}>
        <Text style={styles.bulletedList}>.</Text>
        <Text style={styles.bulletedListText}>
          I acknowledge that insights and educational materials generated by the app are not substitutes for 
          professional medical advice, diagnosis, or treatment, 
          and that I should consult a qualified healthcare provider for all medical concerns.
        </Text>
      </View>
      <View style={styles.bulletedListContainer}>
        <Text style={styles.bulletedList}>.</Text>
        <Text style={styles.bulletedListText}>
        I understand that AI-generated content may not always be accurate, 
        and the developers are not responsible for any actions I take based on this content.
        </Text>
      </View>
      <Text style={styles.commonText}>
        By clicking "I Agree," I confirm I have read and understood this information.
      </Text>
      <TouchableOpacity 
      style={styles.button}
      onPress={handleSubmit}
      >
        <Text style={styles.commonText}>I agree</Text>
      </TouchableOpacity>
    </View>
  );
}

export default ConsentForm;

const styles = StyleSheet.create({
  container: {
    margin: 10, 
    padding: 10
  }, 
  heading: {
    alignSelf: "center", 
    fontSize: 20, 
    fontWeight: "bold"
  },
  commonText: {
    fontSize: 16, 
    fontWeight: 400
  },
  bulletedListContainer: {
    flexDirection: "row"
  },
  bulletedList: {
    fontSize: 24, 
    fontWeight: 800
  },
  bulletedListText: {
    fontSize: 16, 
    fontWeight: 400, 
    marginLeft: 10
  },
  button: {
    alignItems: "center", 
    padding: 10, 
    backgroundColor: "#00bfff"
  }
})